##		Dpckerfile-Api

### BASE STAGE #################################################################
###
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

WORKDIR /app

EXPOSE 8080

ENV ASPNETCORE_URLS=http://*:8000

USER app

### BUILD STAGE ################################################################
###
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY EF_API_DOCK_V4.csproj ./

RUN dotnet restore EF_API_DOCK_V4.csproj

COPY . .

WORKDIR "/src/."

RUN dotnet build EF_API_DOCK_V4.csproj -c Release -o /app/build

### PUBLISH STAGE ##############################################################
###
FROM build AS publish

RUN dotnet publish EF_API_DOCK_V4.csproj -c Release -o /app/publish -p:UseAppHost=false

### FINAL STAGE ################################################################
###
FROM base AS final

WORKDIR /app

COPY --from=publish /app/publish .

CMD dotnet EF_API_DOCK_V4.dll
