##		Dockerfile-Db

### BASE STAGE #################################################################
###
FROM mcr.microsoft.com/mssql/server:2022-latest

WORKDIR /usr/src/app

COPY . /usr/src/app

ENV SA_PASSWORD=L0ckandK#y

ENV ACCEPT_EULA=Y

ENV MSSQL_PID=Developer

EXPOSE 1433

CMD ["./PersonDb/entrypoint.sh"]
